### ISSUE TITLE
Dbus type '\x00' is unknown

### ISSUE THREAD

**Issue by IB1387** [python-sdbus/python-sdbus#12]
Hi, I'm working with the bluez bindings I created (see [here](https://github.com/python-sdbus/python-sdbus-bluez/issues/1)) and am currently dealing with some instabilities. One of the issues that's popping up (seemingly) at random is the following exception:

Traceback (most recent call last):
  File "bt.py", line 273, in handle_properties_changed
    async for path, changed_properties, invalidated_properties in self._device_proxy.properties_changed:
  File "/usr/local/lib/python3.9/dist-packages/sdbus/dbus_proxy_async.py", line 505, in \_\_aiter\_\_
    yield cast(T, next_signal_message.get_contents())
TypeError: Dbus type '\x00' is unknown

This happens when asynchronously listening to signals (I mostly use the properties_changed one). I've already upgraded to sdbus==0.9.0. Does somebody have any idea what's going on?

**Comment by igo95862** [comment]
Can you post your `bt.py` file?

I feel like BlueZ is returning an incorrect type.

**Comment by IB1387** [comment]
I'm not quite comfortable to publicly share ~800 lines code that I wrote for my employer. If it's really needed, I can share the class with you privately. I've put the relevant method below. This is just invoked as a task every time a certain kind of bluetooth device is discovered. The task is cancelled when said device is lost. To detect discovery/lost I listen to the bluez object manager interface added/removed signals.

```
    async def handle_properties_changed(self):
        async for path, changed_properties, invalidated_properties in self._device_proxy.properties_changed:
            if "ServicesResolved" in changed_properties:
                if (
                    len(changed_properties["ServicesResolved"]) >= 2
                    and changed_properties["ServicesResolved"][1]
                ):
                    self._services_resolved_event.set()
                else:
                    self._services_resolved_event.clear()

            if "Connected" in changed_properties:
                if (
                    len(changed_properties["Connected"]) >= 2
                    and changed_properties["Connected"][1]
                ):
                    self._device_connected_event.set()
                else:
                    self._device_connected_event.clear()
```

**Comment by igo95862** [comment]
Hmm. Can you insert: 

```python
next_signal_message.dump()
````

Some where here:

https://github.com/python-sdbus/python-sdbus/blob/061244624e21f4b75ffd247b2c71f776886b5908/src/sdbus/dbus_proxy_async.py#L504

This should dump the contents of the message using the sd-bus internal function.

**Comment by igo95862** [comment]
> object manager interface added/removed signals

But that should be `self._device_proxy.interfaces_added` not  `self._device_proxy.properties_changed` as posted in your method?

**Comment by igo95862** [comment]
Object Manager should be located at root `/` if I am reading bluez code correctly.

Some thing like this: ` manager = DbusObjectManagerInterfaceAsync.new_proxy('org.bluez', '/')`

**Comment by igo95862** [comment]
```
yield cast(T, next_signal_message.get_contents())
TypeError: Dbus type '\x00' is unknown
```
This error basically means that the signal's D-Bus message type was NULL. I am pretty certain this is a BlueZ issue.

You can try to do the `try: expect:` block there you catch the `TypeError` and check the `.args` for that specific error message.

> I can try, though it's a bit hard because the error is not appearing often.

Maybe put dump in to `try: except TypeError:`? So that it would only get dumped if it `

**Comment by IB1387** [comment]
Could finally reproduce the error. Read your "dump twice" remark too late - do I need to try again or does this help?

```‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=110216
  Sender=:1.7  Path=/org/bluez/hci0/dev_C4_16_17_00_00_F7  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.7
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
          };
          ARRAY "s" {
                  STRING "RSSI";
          };
  };
<class 'TypeError'>
Dbus type '\x00' is unknown```

**Comment by igo95862** [comment]
> do I need to try again or does this help?

This seems to be correct capture.

I will try to recreate this message and test if causes same issue.

It looks like correct message so there could be an issue with inside my library. (that empty dict look like could cause some issues)

**Comment by IB1387** [comment]
Had a bunch of these one after another when connecting to multiple devices:

```
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=145
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
          };
          ARRAY "s" {
                  STRING "RSSI";
          };
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=145
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
          };
          ARRAY "s" {
                  STRING "RSSI";
          };
  };

Dbus type '\x00' is unknown
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=155
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "Connected";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=155
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "Connected";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

Dbus type '\x00' is unknown
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=172
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "UUIDs";
                          VARIANT "as" {
                                  ARRAY "s" {
                                          STRING "00000001-0000-4d6f-7469-111122223333";
                                          STRING "00000002-0000-4d6f-7469-111122223333";
                                          STRING "00000003-0000-4d6f-7469-111122223333";
                                          STRING "00000004-0000-4d6f-7469-111122223333";
                                  };
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "ServicesResolved";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=172
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "UUIDs";
                          VARIANT "as" {
                                  ARRAY "s" {
                                          STRING "00000001-0000-4d6f-7469-111122223333";
                                          STRING "00000002-0000-4d6f-7469-111122223333";
                                          STRING "00000003-0000-4d6f-7469-111122223333";
                                          STRING "00000004-0000-4d6f-7469-111122223333";
                                  };
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "ServicesResolved";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

Dbus type '\x00' is unknown
2022-04-19 17:50:46,359 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Error while connecting to device BluetoothDevice[MMG5-228]. Error with DBUS device connection: Software caused connection abort
2022-04-19 17:50:46,396 MainProcess  services.bt                 WARNING  Removed BT device BluetoothDevice[MMG5-228] to retry connection.
2022-04-19 17:50:50,873 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-232].
2022-04-19 17:50:50,972 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-235].
2022-04-19 17:50:51,458 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-238].
2022-04-19 17:50:51,520 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-227].
2022-04-19 17:50:51,620 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-236].
2022-04-19 17:50:51,756 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-231].
2022-04-19 17:50:51,785 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting for device discovery of device BluetoothDevice[MMG5-230].
2022-04-19 17:50:51,842 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-233].
2022-04-19 17:50:51,986 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-237].
2022-04-19 17:50:52,030 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-234].
2022-04-19 17:50:52,172 MainProcess  services.bt                 WARNING  Connect failure on try 2 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-228].
2022-04-19 17:50:52,657 MainProcess  services.bt                 WARNING  Connect failure on try 1 of 5: Timed out waiting to resolve services of device BluetoothDevice[MMG5-229].
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=324
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "ServicesResolved";
                          VARIANT "b" {
                                  BOOLEAN false;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=324
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "ServicesResolved";
                          VARIANT "b" {
                                  BOOLEAN false;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

Dbus type '\x00' is unknown
2022-04-19 17:50:52,697 MainProcess  services.bt                 WARNING  Removed BT device BluetoothDevice[MMG5-232] to retry connection.
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=327
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "Connected";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=327
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "Connected";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

Dbus type '\x00' is unknown
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=329
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "ServicesResolved";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=329
  Sender=:1.8  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.8
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "ServicesResolved";
                          VARIANT "b" {
                                  BOOLEAN true;
                          };
                  };
          };
          ARRAY "s" {
          };
  };

Dbus type '\x00' is unknown

```

**Comment by igo95862** [comment]
All of those are proper messages.

Ideally GDB (GNU debugger) would be really helpful here.

Unfortunately using it is pretty complicated. First you have to compile the C code with debug information. I don't have support for that in the build system. However, that might be a good reason to add that.

**Comment by igo95862** [comment]
> I'm currently integrating USB functionality using sdbus and UDisks2. Are you interested in the generated code?

Yes, after I will be finished with BlueZ binds.

**Comment by igo95862** [comment]
I will try to replicate with my own Bluetooth devices.

**Comment by igo95862** [comment]
By the way what BlueZ version are you using.

**Comment by IB1387** [comment]
It's version 5.55-3.1+rpt1. I'm using the most current stock RaspberryPiOS Lite on a CM4.
`Linux test-device 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux`

Let me know if you need my code so I can share it with you privately. Though I'll be slow to respond until tomorrow morning. I'll be closing my laptop for today.

**Comment by igo95862** [comment]
> armv7l

Hmm. I have not tested against this platform before.

Can you try running unit test suit? I wonder if it will have any errors.

**Comment by IB1387** [comment]
Unit tests seem to run fine. When I originally tried python-sdbus I did it on a 64bit OS, when debugging the original issue where I couldn't get it to run, I tried to switch to 32bit. When you helped me getting it running, I never switched back to 64bit.

```
Ran 84 tests in 2.756s

OK (skipped=4)
```

I'm running the tests with `PYTHON_SDBUS_TEST_LEAKS=1`, but that seems to take a while.

**Comment by igo95862** [comment]
> When I originally tried python-sdbus I did it on a 64bit OS, when debugging the original issue where I couldn't get it to run, I tried to switch to 32bit.

Would be interesting to test if same error appears on 64bit.

> I'm running the tests with `PYTHON_SDBUS_TEST_LEAKS=1`, but that seems to take a while.

That option is kind of very dumb. It runs same tests over million times and I would monitor the memory usage of the python process.

**Comment by IB1387** [comment]
> It runs same tests over million times and I would monitor the memory usage of the python process.
The leak tests passed as well.
```
Ran 84 tests in 4594.873s
OK
```




> Would be interesting to test if same error appears on 64bit.

I will reflash the OS and try again. I've had another exception and error message appearing late yesterday that might or might not be related to the \x00 thing. I skipped it by accident though, so I need to wait until it comes back up to analyze it further.

**Comment by IB1387** [comment]
I've had the \x00 issue reappear using 64bit RaspberryPiOS:
`Linux momidock-1236 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`

I re-applied the dump commands in the installed library and am trying to provoke the issue again. Though I don't think there will be any difference compared to the output from before.

**Comment by IB1387** [comment]
I've had the other issue appear again: 
```
2022-04-20 11:13:24,189 MainProcess  asyncio                     ERROR    Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pi/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/pyfi/main.py", line 133, in <module>
    loop.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1882, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/pyfi/main.py", line 54, in main
    dock = await create_dock_by_config(GLOBAL_CONFIG["dock"])
  File "/opt/pyfi/hardware/__init__.py", line 66, in create_dock_by_config
    return await dock_type_class.create(dock_config)
  File "/opt/pyfi/hardware/gen5dock.py", line 232, in create
    dock._hubs[hub_id] = await create_hub_by_config(
  File "/opt/pyfi/hardware/hubs/__init__.py", line 85, in create_hub_by_config
    return await hub_type_class.create(hub_config, hub_id, dock)
  File "/opt/pyfi/hardware/hubs/LRTS5Hub.py", line 46, in create
    hub._sensors = {
  File "/opt/pyfi/hardware/hubs/LRTS5Hub.py", line 47, in <dictcomp>
    sensor: await EXLs5.create(hub_config["sensors", sensor], sensor, hub, hub._hub_leds)
  File "/opt/pyfi/hardware/hubs/devices/EXLs5.py", line 63, in create
    exls5._bt_device = await (
  File "/opt/pyfi/services/bt.py", line 812, in register_device_by_name
    await new_device._update_dbus_path(path)
  File "/opt/pyfi/services/bt.py", line 253, in _update_dbus_path
    self._properties_changed_task = asyncio.create_task(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 361, in create_task
    task = loop.create_task(coro)
task: <Task pending name='BTService_MMG5-230_properties_changed' coro=<BluetoothDevice.handle_properties_changed() done, defined at /opt/pyfi/services/bt.py:273> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9ee099a0>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> created at /usr/lib/python3.9/asyncio/tasks.py:361>
2022-04-20 11:13:24,204 MainProcess  asyncio                     ERROR    Task exception was never retrieved
future: <Task finished name='Task-11' coro=<<async_generator_athrow without __name__>()> exception=RuntimeError('aclose(): asynchronous generator is already running') created at /usr/lib/python3.9/asyncio/events.py:80>
source_traceback: Object created at (most recent call last):
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/pi/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pi/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/pyfi/main.py", line 133, in <module>
    loop.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1882, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: aclose(): asynchronous generator is already running
```

It seems to be directly correlated, as I've received the dump right after:
```
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=13704  Timestamp="Wed 2022-04-20 10:13:26.069104 UTC"
  Sender=:1.7  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.7
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
          };
          ARRAY "s" {
                  STRING "RSSI";
          };
  };
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=13704  Timestamp="Wed 2022-04-20 10:13:26.069409 UTC"
  Sender=:1.7  Path=/org/bluez/hci0/dev_C4_16_17_00_00_E8  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.7
  MESSAGE "sa{sv}as" {
          STRING "org.bluez.Device1";
          ARRAY "{sv}" {
          };
          ARRAY "s" {
                  STRING "RSSI";
          };
  };
Dbus type '\x00' is unknown
```

This is all using 64bit now - to my eye there doesn't seem to be a difference to 32bit.

**Comment by igo95862** [comment]
Looks extemely similar to the issue here:

https://github.com/python-sdbus/python-sdbus/issues/5#issuecomment-893451569

Which was caused by tasks not being bounds to variables and getting garbage collected.

**Comment by IB1387** [comment]
True, tasks being garbage collected was a pitfall I had problems with before. ~I'm pretty sure that no task variable should fall out of scope now.~ 
Correction: I think I found one edge case where the task that monitors the properties_changed signal could be replaced with a new one without being cancelled first. I couldn't reproduce the issue for 30 minutes, so let's keep our fingers crossed.

**Comment by igo95862** [comment]
🤞

**Comment by igo95862** [comment]
> Thanks a ton for your help! Is there a way (paypal/github sponsor/etc.) in which can buy you a beer? smiley

Unfortunately not possible currently. All of those services stopped working in my region. (guess which region it is)
