### ISSUE TITLE
Trigger Multiple Return Values

### ISSUE THREAD

**Issue by wes8ty** [python-sdbus/python-sdbus#19]
Hello,

Still working on the BLE stuff porting things over and I was wondering if there was a way to return multiple "values" for a single async call to `read_value()`. This is the characteristic method for Bluez. In my previous implementation, I need to return a list that is too large for a single MTU for BLE. I got around this by returning a single item in the list and triggering a properties changed without exiting the method in a loop.

`Old Way`
``` py
self.PropertiesChanged(BtEnum.GATT_CHRC_IFACE, {'Value': value}, [])

@dbus.service.signal(BtEnum.DBUS_PROP_IFACE, signature="sa{sv}as")
    def PropertiesChanged(self, interface, changed, invalidated):
        pass
```

I saw that you have a `properties_changed()` method in `DbusPropertiesInterfaceAsync` and I also saw this code bit where I think you are performing that function but mine is a method though.

``` py
if self.dbus_property.properties_changed_signal is not None:
    assert self.dbus_property.interface_name is not None
    self.dbus_property.properties_changed_signal.emit(
        (
            self.dbus_property.interface_name,
            {
                self.dbus_property.property_name: (
                    self.dbus_property.property_signature,
                    data_to_set_to,
                ),
            },
            []
        )
    )
```

**Comment by igo95862** [comment]
Are you talking about this `ReadValue`: https://github.com/bluez/bluez/blob/1ffd74a6d4212a165763dc53e58a1b49b6fc5a98/doc/gatt-api.txt#L72

That method returns bytes not a list.


> I got around this by returning a single item in the list and triggering a properties changed without exiting the method in a loop.

So what ever is calling that method will when listen for properties changed and call the method again? (sound like some horrible hacks)

Anyway you can just emit the signal manually:

```python
# Properties changed signal returns 3 elements
# 1. interface name
# 2. Changed properties with new values: Dict with keys string and values variants
# 3. Names of invalidated properties:  List of string
self.properties_changed.emit(
     'org.example.interface',  # dbus interface name
     {'some_property':  # property name in dbus
           ('s' ,  # property dbus type
           'property_value')  # property value
     },
    [],  # invalidated properties
)
```

**Comment by wes8ty** [comment]
Hey @igo95862,

Thanks for the quick reply. You are correct that it is `ReadValue` and returns bytes. So I tried your code but got this error

```
2022-06-08 14:45:33,865 [base_events.py      :1753] [asyncio                       ] [ERROR] Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DbusMethodAsyncBinded._call_from_dbus() done, defined at /usr/local/lib/python3.9/site-packages/sdbus/dbus_proxy_async.py:140> exception=TypeError('emit() takes 2 positional arguments but 4 were given')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sdbus/dbus_proxy_async.py", line 157, in _call_from_dbus
    reply_data = await local_method(request_data)
  File "/usr/src/app/cnsmngr/ble/torus_services.py", line 129, in read_value
    return await self.__read_val_cbk()
  File "/usr/src/app/cnsmngr/ble/ble_manager.py", line 264, in ssid_lst_char_read_val_cbk
    self.__ble_ssid_lst_char.properties_changed.emit(Ble.IFACE_GATT_CHRC, {"read_value": ("ay", value)}, [])
TypeError: emit() takes 2 positional arguments but 4 were given
```

I saw in other examples that you encompass the entire argument with `()` So I did that with this statement in which 
``` py
self.__ble_ssid_lst_char.properties_changed.emit(("org.bluez.GattCharacteristic1", {"ReadValue": ("ay", value)}, []))
```

I got this error though which means `ENOMSG No message of the desired type (POSIX.1-2001).`

```
2022-06-08 14:49:01,895 [base_events.py      :1753] [asyncio                       ] [ERROR] Task exception was never retrieved
future: <Task finished name='Task-7' coro=<DbusMethodAsyncBinded._call_from_dbus() done, defined at /usr/local/lib/python3.9/site-packages/sdbus/dbus_proxy_async.py:140> exception=SdBusLibraryError('File: src/sdbus/sd_bus_internals_message.c Line: 709. sd_bus_send(((void *)0), self->message_ref, ((void *)0)) in function SdBusMessage_send returned error number: 42')>
```

**Comment by igo95862** [comment]
This is probably what sdbus errors about:
```
-ENOMSG
           The D-Bus message m is a reply but its type signature does not
           match the return type signature of its corresponding member in the
           object vtable.
```

It might be that sdbus sees that `"ReadValue"` is a method but you are sending it as a property.

To be honest you probably need a low-level API to create these horrible hacks. I don't have it stabilized or documented. It is located in `sdbus.sdbus_internals`. You can look at the typing stub `sdbus/sd_bus_internals.py` as a rough guide.

**Comment by wes8ty** [comment]
So I made a mistake on the value conversion `bytes` instead of `bytearray` that caused the error `ENOMSG`. Where did not find that specific description? I could only find [this](https://www.man7.org/linux/man-pages/man3/errno.3.html).

``` py
value = bytearray(network.SerializeToString())
self.__ble_ssid_lst_char.properties_changed.emit(("org.bluez.GattCharacteristic1", {"ReadValue": ("ay", value)}, []))
```
So the good news is I am not getting any errors with that line above. The bad news is I am not seeing any dbus traffic when that line is called only the returned value I am sending at the end of the method.

```
method call time=1654702326.434952 sender=:1.11 -> destination=:1.616 serial=2234 path=/org/bluez/torus/services/cns/ssidlst; interface=org.bluez.GattCharacteristic1; member=ReadValue
   array [
      dict entry(
         string "device"
         variant             object path "/org/bluez/hci0/dev_69_C0_6E_42_57_73"
      )
      dict entry(
         string "link"
         variant             string "LE"
      )
      dict entry(
         string "mtu"
         variant             uint16 517
      )
   ]
method return time=1654702327.938844 sender=:1.616 -> destination=:1.11 serial=5955 reply_serial=2234
   array of bytes [
      0a
   ]
```

So how could the old method do this?
``` py
self.PropertiesChanged(BtEnum.GATT_CHRC_IFACE, {'Value': value}, [])

@dbus.service.signal(BtEnum.DBUS_PROP_IFACE, signature="sa{sv}as")
    def PropertiesChanged(self, interface, changed, invalidated):
        pass
```

**Comment by wes8ty** [comment]
So I figured it out by comparing it to the old implemantion. The line should be

``` py
self.__ble_ssid_lst_char.properties_changed.emit(("org.bluez.GattCharacteristic1", {"Value": ("ay", value)}, []))
```
However, notifications need to be enabled `start_notify` before the method is called so the change of the method property is sent to the device automatically. So it is possible to do this with the `properties_changed.emit()` method. Thanks for the help! This "hack" was copied from Bluez code (old way)...lol
