### ISSUE TITLE
TypeError when using catch_anywhere

### ISSUE THREAD

**Issue by IB1387** [python-sdbus/python-sdbus#45]
Hi! 
We are using dbus bindings for bluez for quite some time already and everything was working smoothly. Now I wanted to add detection of the online state of our device using the DBus interface of systemd-networkd. That means, that we have an additional coroutine listening for property_changed signals on the OrgFreedesktopNetwork1ManagerInterface. Whenever something happens with the networkd properties, we get an exception with the bluez property listener: 
```
Traceback (most recent call last):
  File "/opt/pyfi/util/multi_dbus_test.py", line 41, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/pyfi/util/multi_dbus_test.py", line 11, in main
    await asyncio.gather(
  File "/opt/pyfi/util/multi_dbus_test.py", line 30, in watch_bluez_properties
    async for path, (
  File "/usr/lib/python3.10/site-packages/sdbus/dbus_proxy_async_signal.py", line 194, in catch_anywhere
    cast(T, next_signal_message.get_contents())
TypeError: Dbus type '\x00' is unknown
```

My colleague found out, that when we use different SYSTEM_BUS objects for each property listener, than everything seems to work as expected. Is using the bus object in different coroutines simultaneosly not supported or have we indeed found a bug?

Heres a minimal example to produce the error. If you replace SYSTEM_BUS in watch_bluez_properties with SYSTEM_BUS2 everything works:
```
from util.dbusutils.networkd_interfaces import OrgFreedesktopNetwork1ManagerInterface
from util.dbusutils.bluez_interfaces import OrgBluezDevice1Interface
import asyncio
import sdbus

SYSTEM_BUS = sdbus.sd_bus_open_system()
SYSTEM_BUS2 = sdbus.sd_bus_open_system()


async def main():
    await asyncio.gather(
        watch_bluez_properties(),
        watch_networkd_properties(),
    )


async def watch_networkd_properties():
    async for path, (
        interface,
        changed_properties,
        invalidated_properties,
    ) in OrgFreedesktopNetwork1ManagerInterface.properties_changed.catch_anywhere(
        service_name="org.freedesktop.network1",
        bus=SYSTEM_BUS,
    ):
        print(f"{path}: {interface} - {changed_properties} - {invalidated_properties}")


async def watch_bluez_properties():
    async for path, (
        interface,
        changed_properties,
        invalidated_properties,
    ) in OrgBluezDevice1Interface.properties_changed.catch_anywhere(
        service_name="org.bluez", bus=SYSTEM_BUS
    ):
        print(f"{path}: {interface} - {changed_properties} - {invalidated_properties}")


if __name__ == "__main__":
    asyncio.run(main())
```

For completeness, here are our networkd and bluez interfaces that were generated using your generator script:
https://pastebin.com/T7zfpGw5
https://pastebin.com/wGPLaqRz

**Comment by igo95862** [comment]
Hello @IB1387 

I remembered that `TypeError: Dbus type '\x00' is unknown` was an error that someone encountered in the past.

I went to issues and realized that it was you:

https://github.com/python-sdbus/python-sdbus/issues/12#issuecomment-1103779140

However, this does not look like cancellation issue.

Someone else looks like discovered the similar issue but in the context of calling the `message.get_contents()` twice.

https://github.com/python-sdbus/python-sdbus/issues/14#issuecomment-1125809166

**Comment by IB1387** [comment]
Hi @igo95862,
with the code I'm able to reproduce the issue 100% of the time on my RaspberryPi CM4 running a 64bit Yocto/Poki based OS. As soon as anything happens (either networkd changing a property because I unplug an ethernet cable or bluez because I e.g. start or stop a scan), the program I posted crashes immediatly with the same error. 

I'm out of the office for today, but just to be sure I test the correct thing tomorrow:

You mean inserting `message.dump()` in the library code for the `catch` and `catch_anywhere` methods?
So before [here](https://github.com/python-sdbus/python-sdbus/blob/c1d9f2f52e2ab4be5e13c295bc36febddf44c476/src/sdbus/dbus_proxy_async_signal.py#L140) and [here](https://github.com/python-sdbus/python-sdbus/blob/c1d9f2f52e2ab4be5e13c295bc36febddf44c476/src/sdbus/dbus_proxy_async_signal.py#L194), correct?

**Comment by igo95862** [comment]
> You mean inserting `message.dump()` in the library code for the `catch` and `catch_anywhere` methods?
> So before [here](https://github.com/python-sdbus/python-sdbus/blob/c1d9f2f52e2ab4be5e13c295bc36febddf44c476/src/sdbus/dbus_proxy_async_signal.py#L140) and [here](https://github.com/python-sdbus/python-sdbus/blob/c1d9f2f52e2ab4be5e13c295bc36febddf44c476/src/sdbus/dbus_proxy_async_signal.py#L194), correct?

Yes, right before `get_contents()` call happens so that the message can be red again.

**Comment by IB1387** [comment]
Inserting `next_signal_message.dump()` before the mentioned lines causes the program to work as intended and not crash anymore.
I captured the following output by running my program and unplugging the ethernet port:
```
> Type=signal  Endian=l  Flags=1  Version=1 Cookie=52  Timestamp="Thu 2023-10-26 08:32:23.961822 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1/link/_32  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Link";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "CarrierState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "OperationalState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "OnlineState";
                          VARIANT "s" {
                                  STRING "offline";
                          };
                  };
          };
          ARRAY "s" {
          };
  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=52  Timestamp="Thu 2023-10-26 08:32:23.962371 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1/link/_32  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Link";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "CarrierState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "OperationalState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "OnlineState";
                          VARIANT "s" {
                                  STRING "offline";
                          };
                  };
          };
          ARRAY "s" {
          };
  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=53  Timestamp="Thu 2023-10-26 08:32:23.981304 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Manager";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "OperationalState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "CarrierState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "OnlineState";
                          VARIANT "s" {
                                  STRING "offline";
                          };
                  };
          };
          ARRAY "s" {
          };
  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=54  Timestamp="Thu 2023-10-26 08:32:23.981634 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1/link/_32  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Link";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "AddressState";
                          VARIANT "s" {
                                  STRING "degraded";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "IPv4AddressState";
                          VARIANT "s" {
                                  STRING "off";
                          };
                  };
          };
          ARRAY "s" {
          };/org/freedesktop/network1/link/_32: org.freedesktop.network1.Link - {'CarrierState': ('s', 'no-carrier'), 'OperationalState': ('s', 'no-carrier'), 'OnlineState': ('s', 'offline')} - []
/org/freedesktop/network1/link/_32: org.freedesktop.network1.Link - {'CarrierState': ('s', 'no-carrier'), 'OperationalState': ('s', 'no-carrier'), 'OnlineState': ('s', 'offline')} - []
/org/freedesktop/network1: org.freedesktop.network1.Manager - {'OperationalState': ('s', 'no-carrier'), 'CarrierState': ('s', 'no-carrier'), 'OnlineState': ('s', 'offline')} - []
/org/freedesktop/network1/link/_32: org.freedesktop.network1.Link - {'AddressState': ('s', 'degraded'), 'IPv4AddressState': ('s', 'off')} - []
/org/freedesktop/network1: org.freedesktop.network1.Manager - {'OperationalState': ('s', 'no-carrier'), 'CarrierState': ('s', 'no-carrier'), 'OnlineState': ('s', 'offline')} - []
/org/freedesktop/network1/link/_32: org.freedesktop.network1.Link - {'AddressState': ('s', 'degraded'), 'IPv4AddressState': ('s', 'off')} - []
/org/freedesktop/network1: org.freedesktop.network1.Manager - {'AddressState': ('s', 'degraded'), 'IPv4AddressState': ('s', 'off')} - []
/org/freedesktop/network1: org.freedesktop.network1.Manager - {'AddressState': ('s', 'degraded'), 'IPv4AddressState': ('s', 'off')} - []

  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=53  Timestamp="Thu 2023-10-26 08:32:23.982097 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Manager";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "OperationalState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "CarrierState";
                          VARIANT "s" {
                                  STRING "no-carrier";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "OnlineState";
                          VARIANT "s" {
                                  STRING "offline";
                          };
                  };
          };
          ARRAY "s" {
          };
  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=54  Timestamp="Thu 2023-10-26 08:32:23.982321 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1/link/_32  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Link";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "AddressState";
                          VARIANT "s" {
                                  STRING "degraded";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "IPv4AddressState";
                          VARIANT "s" {
                                  STRING "off";
                          };
                  };
          };
          ARRAY "s" {
          };
  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=55  Timestamp="Thu 2023-10-26 08:32:23.982988 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Manager";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "AddressState";
                          VARIANT "s" {
                                  STRING "degraded";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "IPv4AddressState";
                          VARIANT "s" {
                                  STRING "off";
                          };
                  };
          };
          ARRAY "s" {
          };
  };

> Type=signal  Endian=l  Flags=1  Version=1 Cookie=55  Timestamp="Thu 2023-10-26 08:32:23.983328 UTC"
  Sender=:1.0  Path=/org/freedesktop/network1  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.freedesktop.network1.Manager";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "AddressState";
                          VARIANT "s" {
                                  STRING "degraded";
                          };
                  };
                  DICT_ENTRY "sv" {
                          STRING "IPv4AddressState";
                          VARIANT "s" {
                                  STRING "off";
                          };
                  };
          };
          ARRAY "s" {
          };
  };
```

Let me know how I can help further!

**Comment by igo95862** [comment]
This is a simple issue that I don't know why I didn't thought about it earlier. The message has an internal state. `get_contents()` parses the message and puts the message cursor to the end. Any new `get_contents()` calls will get the message that is already scrolled to the end.

The obvious fix is to rewind the message before parsing it. I want to add this fix and a few interface generator fixes and release the 0.11.1 version.

**Comment by IB1387** [comment]
Sounds good! Let me know when the release is ready. I'll test it, report back and we can close the issue. 👍

**Comment by igo95862** [comment]
[Version 0.11.1 released](https://github.com/python-sdbus/python-sdbus/releases/tag/0.11.1)

It should fix reading from the same message multiple times.

**Comment by IB1387** [comment]
Sure, I will probably be able to test on monday.

**Comment by IB1387** [comment]
I finally got around testing the new release. The test program I've posted ran without issue on 0.11.1 for a few minutes with continous scanning and changes to the network interfaces producing DBus signals. Downgrading to 0.11.0 makes the exception immediately show up again. For me this issue seems fixed!

Thanks a lot for your work and the quick release!
