### ISSUE TITLE
Exceptions when using signals (asyncio)

### ISSUE THREAD

**Issue by satirebird** [python-sdbus/python-sdbus#5]
First of all, thank you for adding the object manager and and the great project. I tried to get it to work with the bluez interface. Currently I have some trouble with the signals. 

I create the following example:

```
import asyncio
import sys
import traceback
from asyncio import get_event_loop
from asyncio import sleep

from sdbus import DbusObjectManagerInterfaceAsync
from sdbus import sd_bus_open_system
from org_bluez_adapter1 import OrgBluezAdapter1Interface

bus = sd_bus_open_system()
om = DbusObjectManagerInterfaceAsync.new_connect('org.bluez', '/', bus)

async def signal_cb():
#    await asyncio.sleep(1)
    async for x in om.interfaces_added:
        print("Added")

async def signal_cb2():
#    await asyncio.sleep(1)
    async for x in om.interfaces_removed:
        print("Removed")

async def scan(timeout: int):
    try:
        objs = await om.get_managed_objects()
    except:
        e = sys.exc_info()[0]
        print("Exception", e)
        traceback.print_exc()
        return
    for path, interface in objs.items():
        if interface is not None:
            for ipath, iv in interface.items():
                if ipath == 'org.bluez.Adapter1':
                    print("Interface found: " + path)
                    adapter = OrgBluezAdapter1Interface.new_connect('org.bluez', path, bus)
                    await adapter.start_discovery()
                    await sleep(timeout)
                    await adapter.stop_discovery()
                    return
    return

loop = get_event_loop()
loop.create_task(scan(10))
loop.create_task(signal_cb())
loop.create_task(signal_cb2())
loop.run_forever()
loop.close()
```

The `OrgBluezAdapter1Interface` is generated from introspection with the [generator](https://python-sdbus.readthedocs.io/en/latest/code_generator.html). The [source](https://gist.github.com/satirebird/b1cfd0414d4b061c4aa7868614fd1b25)

If I execute the script the method `get_managed_objects()` generates an exception.

```
Exception <class 'GeneratorExit'>
Traceback (most recent call last):
  File "/home/sven/workspaces/lt_ble/pytest/test-sdbus.py", line 26, in scan
    objs = await om.get_managed_objects()
GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<scan() done, defined at /home/sven/workspaces/lt_ble/pytest/test-sdbus.py:24> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f12dde9cc70>()]>>
```

The strange thing is, that it is timing sensitive. Sometimes it works and sometimes not. If I try to debug it, including a breakpoint it works all the time. If I un-comment the `await asyncio.sleep(1)` it also works. I guess that there are some synchronization issues in the library.

The library version is 0.8.1 from PyPI

**Comment by igo95862** [comment]
> First of all, thank you for adding the object manager and and the great project.

You are welcomed.


I found some bug reports that look very similar:

https://bugs.python.org/issue30083
https://bugs.python.org/issue35409

```
    try:
        objs = await om.get_managed_objects()
    except:
        e = sys.exc_info()[0]
        print("Exception", e)
        traceback.print_exc()
        return
```

This code looks really spooky.

Does the issue still persists if  there is no try except block?

Or maybe try something like this:

`from sdbus import SdBusBaseError`

```
   try:
        objs = await om.get_managed_objects()
    except SdBusBaseError as e:
        print('sdbus error:', e)
        return

```

I will also try to run this on my machine to test.

**Comment by satirebird** [comment]
It also happens without any try / except block. The task stops working with:
```
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<scan() done, defined at /home/sven/workspaces/lt_ble/pytest/test-sdbus.py:24> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9356d8ad00>()]>>
```
> This code looks really spooky.

Yes. I added it only for testing. I found it [here](https://wiki.python.org/moin/HandlingExceptions) to catch everyting. The exception class is `GeneratorExit`. Your suggestion to catch `SdBusBaseError` doen't work.

Python version 3.8.10 on Ubuntu 20.04

If I enable `loop.set_debug(True)` I cannot reproduce the behavior with the test. But on my other application it still crashes with a trace which seems not very useful:
```
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 36, in <module>
    main()
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 26, in main
    lsdbus.start_task(loop)
  File "/home/sven/workspaces/lt_ble/pytest/live_sdbus.py", line 55, in start_task
    loop.create_task(self.__added())
task: <Task pending name='Task-2' coro=<LiveSDbus.__added() done, defined at /home/sven/workspaces/lt_ble/pytest/live_sdbus.py:28> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5c6c88d190>()] created at /usr/lib/python3.8/asyncio/base_events.py:422> created at /home/sven/workspaces/lt_ble/pytest/live_sdbus.py:55>
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 36, in <module>
    main()
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 26, in main
    lsdbus.start_task(loop)
  File "/home/sven/workspaces/lt_ble/pytest/live_sdbus.py", line 56, in start_task
    loop.create_task(self.__removed())
task: <Task pending name='Task-3' coro=<LiveSDbus.__removed() done, defined at /home/sven/workspaces/lt_ble/pytest/live_sdbus.py:33> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5c6c88d250>()] created at /usr/lib/python3.8/asyncio/base_events.py:422> created at /home/sven/workspaces/lt_ble/pytest/live_sdbus.py:56>
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<<async_generator_athrow without __name__>()> exception=RuntimeError('aclose(): asynchronous generator is already running') created at /usr/lib/python3.8/asyncio/events.py:81>
source_traceback: Object created at (most recent call last):
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 36, in <module>
    main()
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 32, in main
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: aclose(): asynchronous generator is already running
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<<async_generator_athrow without __name__>()> exception=RuntimeError('aclose(): asynchronous generator is already running') created at /usr/lib/python3.8/asyncio/events.py:81>
source_traceback: Object created at (most recent call last):
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 36, in <module>
    main()
  File "/home/sven/workspaces/lt_ble/pytest/live-ble.py", line 32, in main
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: aclose(): asynchronous generator is already running
```

**Comment by igo95862** [comment]
Hmm. It could be that garbage collection destroys the tasks. (https://github.com/encode/uvicorn/pull/972) Would you mind test giving created tasks variable names?

```
scan_task = loop.create_task(scan(10))
signal_task1 = loop.create_task(signal_cb())
signal_task2 = loop.create_task(signal_cb2())
```

**Comment by satirebird** [comment]
Oh my goodness!. That's it. I didn't know that. Thank you very much!

BTW: you should update your examples as well. It looks like this :smirk: 
```
loop.create_task(clock())
loop.run_forever()
```

**Comment by igo95862** [comment]
> BTW: you should update your examples as well. It looks like this smirk

I will.

Does your other application still crash?

**Comment by satirebird** [comment]
No, It works like a charm.

**Comment by igo95862** [comment]
I guess I will work on Bluez binds next. The auto-generated code is pretty rough around edges and needs some hand polish. (the `u_u_i_d` method for example)
