### ISSUE TITLE
`sdbus.utils.parse_get_managed_objects()` seems to be broken

### ISSUE THREAD

**Issue by m1stadev** [python-sdbus/python-sdbus#74]
Hi, i'm attempting to write BlueZ bindings using the latest PyPI release of `sdbus`. When I try to grab all objects from the service and pass it to `parse_get_managed_objects()`, it fails to parse the data.

My code:
```py
import asyncio
from sdbus import sd_bus_open_system, DbusObjectManagerInterfaceAsync
from sdbus.utils import parse_get_managed_objects
from pybluez.interfaces import Device, AgentManager, HealthChannel, HealthDevice, HealthManager, ProfileManager

async def main():
    dbus = sd_bus_open_system()
    om = DbusObjectManagerInterfaceAsync.new_proxy('org.bluez', '/', bus=dbus)

    objects = await om.get_managed_objects()
    parsed_objects = parse_get_managed_objects((Device, AgentManager, HealthChannel, HealthDevice, HealthManager, ProfileManager), objects)
    for obj in parsed_objects:
        print(obj)

if __name__ == '__main__':
    asyncio.run(main())```

The error:
```Traceback (most recent call last):
  File "/home/m1sta/dbus/bluez_client.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/m1sta/dbus/bluez_client.py", line 11, in main
    parsed_objects = parse_get_managed_objects((Device, AgentManager, HealthChannel, HealthDevice, HealthManager, ProfileManager), objects)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m1sta/dbus/.venv/lib/python3.11/site-packages/sdbus/utils.py", line 245, in parse_get_managed_objects
    _get_class_from_interfaces(
  File "/home/m1sta/dbus/.venv/lib/python3.11/site-packages/sdbus/utils.py", line 126, in _get_class_from_interfaces
    return interfaces_to_class_map[class_set]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: frozenset({'org.bluez.ProfileManager1', 'org.bluez.AgentManager1', 'org.bluez.HealthManager1'})
```

The `_get_class_from_interfaces()` function in the `utils` module is trying to use an iterator that contains multiple interface names as a key for the `interfaces_to_class_map` dict, but `interfaces_to_class_map` only contains keys for single interfaces.

**Comment by igo95862** [comment]
Hello @m1stadev 

```python
KeyError: frozenset({'org.bluez.ProfileManager1', 'org.bluez.AgentManager1', 'org.bluez.HealthManager1'})
```

What this means is that there is an object that combines those three interfaces.

```python
(Device, AgentManager, HealthChannel, HealthDevice, HealthManager, ProfileManager)
```

It looks like you are passing the interfaces separately? You will need a class that combines `AgentManager`, `ProfileManager` and `HealthManager`.

```python

class Manager(AgentManager, ProfileManager, HealthManager):
    ...
```

**Comment by igo95862** [comment]
@m1stadev any updates?

**Comment by m1stadev** [comment]
I ended up not needing the functionality of those interfaces for what I'm working on, so I just left it alone.
